### ISSUE TITLE
Uncaught TypeError: e.isLighter is not a function

### ISSUE THREAD

**Issue by newredstone02** [AlexTorresDev/custom-electron-titlebar#192]
**Describe the bug**
The whole titlebar frezzes and trows this error

`Uncaught TypeError: e.isLighter is not a function`

**Desktop (please complete the following information):**
 - Windows 10 21H1
 - Electron v15.3.0
 - Node v16.5.0

**Comment by AlexTorresSk** [comment]
Does this still show up in the latest version of CET?

**Comment by KK-Designs** [comment]
> Does this still show up in the latest version of CET?

I'm getting the same error, I'm on windows 11 stable

![image](https://user-images.githubusercontent.com/71038229/205514251-12201aab-ef99-43e4-b12a-6c48f0bc4225.png)

**Comment by KK-Designs** [comment]
@newredstone02 when choosing the background color for the title bar using
```js
const { Titlebar, Color } = require('custom-electron-titlebar');

new Titlebar({ backgroundColor: Color.fromHex('#3a3b3c') });
```
works instead of the direct hex code.
