### ISSUE TITLE
Production cannot find module `custom-electron-titlebar/main`

### ISSUE THREAD

**Issue by BryanYin** [AlexTorresDev/custom-electron-titlebar#202]
**Describe the bug**
I'm using latest version 4.1.3 and get below exception when running in release mode. Dev and debug mode does not have such issue.
<img width="520" alt="image" src="https://user-images.githubusercontent.com/25950822/206682401-53638f21-9c86-4b10-9656-3f2a1d32fb98.png">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura and Windows
 - Electron version 21.1.1
 - Node Version v16.18.1

**Comment by pankaj2k9** [comment]
I am getting the same issue.

**Comment by AlexTorresDev** [comment]
> **Describe the bug**
> I'm using latest version 4.1.3 and get below exception when running in release mode. Dev and debug mode does not have such issue.
> <img width="520" alt="image" src="https://user-images.githubusercontent.com/25950822/206682401-53638f21-9c86-4b10-9656-3f2a1d32fb98.png">
> 
> 
> **Desktop (please complete the following information):**
>  - OS: MacOS Ventura and Windows
>  - Electron version 21.1.1
>  - Node Version v16.18.1
> 

Are you using electron-builder to build project?

**Comment by BryanYin** [comment]
Hi, I was using https://github.com/maximegris/angular-electron as project template.

The issue was resolved by adding `custom-electron-titlebar` to `app/package.json`.

**Comment by AlexTorresDev** [comment]
Fixed on last version
