### ISSUE TITLE
Module not found: Error: Can't resolve 'custom-electron-titlebar/main' in...

### ISSUE THREAD

**Issue by PierreLeGit** [AlexTorresDev/custom-electron-titlebar#212]
Hello, I try tu use this library but i cannot launch my app.
The error is 
Module not found: Error: Can't resolve 'custom-electron-titlebar/main' in "path of my app"src\main
   @ ./src/main/main.ts 7:0-86 8:0-13 126:4-26
   @ multi ./node_modules/electron-webpack/out/electron-main-hmr/main-hmr ./src/main/main.ts

Do you have an idea?
Regards.

**Comment by PierreLeGit** [comment]
I've tried to add in webpack.config but error still here:
  resolve: {
    extensions: ['.js', '.jsx', '.ts', '.tsx'],
  },

**Comment by AlexTorresDev** [comment]
Fixed on last version
