### ISSUE TITLE
Menu is quadruplicated on screen

### ISSUE THREAD

**Issue by lvcabral** [AlexTorresDev/custom-electron-titlebar#213]
**Describe the bug**
After upgrading to 4.2.1 the Menu is showing repeated 4 times

**To Reproduce**
Open the created Window

**Expected behavior**
Only one instance of the menu is displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/16841645/236986735-ec99b2af-853e-4a73-be53-fc11bb699477.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Electron version: 20.3.2
 - Node Version: 18.14.2

**Comment by AlexTorresDev** [comment]
You can add code of the implementation of the title bar and creation of the menu to replicate the error
