### ISSUE TITLE
Separate Title Bar and Menu Bar

### ISSUE THREAD

**Issue by cruzjuniel** [AlexTorresDev/custom-electron-titlebar#22]
I'm looking to use this with [Carlo](https://github.com/GoogleChromeLabs/carlo) from GoogleChromeLabs
Are there plans to separate the Menu bar from the Title bar?

Currently, I plan to utilize this while Carlo has no support for Frameless Window like Electron. I'm thinking of simply hiding the whole title bar element for now using simple CSS styles.

It would be great if they can be separated so we can use one without the other.

**Comment by AlexTorresSk** [comment]
For now I do not plan to separate the title bar from the menu bar.

At this time you can use CSS styles to hide everything you do not need.

**Comment by amanharwara** [comment]
```css
.window-title, .window-controls-container {
    display: none !important;
}
```

This CSS should do the trick.
