### ISSUE TITLE
Error setting background color

### ISSUE THREAD

**Issue by eldeesmith** [AlexTorresDev/custom-electron-titlebar#224]
custom-electron-titlebar\dist\titlebar\index.js:290 Uncaught TypeError: backgroundColor?.isLighter is not a function`

**Comment by AlexTorresDev** [comment]
Attach the implementation code for the title bar you used

**Comment by AlexTorresDev** [comment]
Fixed on [v4.2.6](https://github.com/AlexTorresDev/custom-electron-titlebar/releases/tag/v4.2.6)
