### ISSUE TITLE
[Windows] Hovering menu two options are highlighted

### ISSUE THREAD

**Issue by lvcabral** [AlexTorresDev/custom-electron-titlebar#225]
**Describe the bug**
When hovering the main menu with the mouse two options are being highlighted at the same time.

**To Reproduce**
1. Go to any application with at least two menu items
2. Hover you mouse over the menu

**Expected behavior**
Only the option under the mouse is highlighted

**Screenshots**
![BrightScript_Emulator_vN1vHiVxeZ](https://github.com/AlexTorresDev/custom-electron-titlebar/assets/16841645/0f21005a-f747-49f3-b2cd-cdc4b5f37adb)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Electron version: 20.0.0
 - Node Version: 18.14.2

**Comment by Memoyll** [comment]
I have also encountered this issue. When can the author fix it? Stay tuned

**Comment by binarynonsense** [comment]
I'm also having the same issue with version 4.2.4 on Linux (Electron v25.3.1).

**Comment by binarynonsense** [comment]
The issue is still present in version 4.2.5, in case it helps.

**Comment by Memoyll** [comment]
请问什么时候能解决？
