### ISSUE TITLE
Menu is placed under titlebar in Linux

### ISSUE THREAD

**Issue by subbota-a** [AlexTorresDev/custom-electron-titlebar#236]
## Problem Description

![Screenshot_20230819_165813](https://github.com/AlexTorresDev/custom-electron-titlebar/assets/17779450/93fbd3b1-052e-4611-8b45-bc349abb8417)
I got this repository, build and run it by `npm run dev` and got double menu and both are under titlebar.

## Steps to Reproduce

Run by `npm run dev`

## Expected Behavior

Expected that menu is in titlebar
![image](https://github.com/AlexTorresDev/custom-electron-titlebar/assets/17779450/1109baad-81da-48d4-9d21-75c7200dfa30)

## Current Behavior

See my screenshot. Double menu both under titlebar

## Additional Information

Fedora 38, Wayland, KDE Plasma 5.27

> **Note:**
bug

**Comment by AlexTorresDev** [comment]
Add `frame: false` to main.js in BrowserWindow properties

**Comment by subbota-a** [comment]
Sorry, @AlexTorresDev , but it is **your** example and your [main.js](https://github.com/AlexTorresDev/custom-electron-titlebar/blob/main/example/main.js) that has to demonstrate how to **properly use** your library and what **result** we have to get. And now you **silently** "fixed" the problem without letting me known and you made a new mistake. You forgot to put the comma. And I think it's better to detect OS automatically, because user from other OS will write you about new bug in example.
