### ISSUE TITLE
The submenus are not aligned with the title menu

### ISSUE THREAD

**Issue by lvcabral** [AlexTorresDev/custom-electron-titlebar#247]
## Problem Description

When we open the top cascading menus, there is a 8px gap between the title and the left edge of the menu.

## Steps to Reproduce

1. Open the app
2. Open any Menu

## Expected Behavior

- Menu is aligned with the top button

## Current Behavior

- Menu is shown 8px to the right

## Tentative Solution Steps

The solution is to get the bounding box of the button and not the title, I will push a PR with it fixed.

## Screenshots
![image](https://github.com/AlexTorresDev/custom-electron-titlebar/assets/16841645/2f586add-37d9-4256-9a47-cfd0a3175d12)

## Additional Context

[Add any other context that might be useful for understanding the issue, such as recent code changes, events that might have triggered the problem, etc.]

> **Note:**
   Labels - "bug"

**Comment by lvcabral** [comment]
@AlexTorresDev when do you plan to make the next release with this fix?

**Comment by AlexTorresDev** [comment]
Fixed in version 4.2.8
