### ISSUE TITLE
Activating the menu using ALT key (enableMnemonics)

### ISSUE THREAD

**Issue by MangaD** [AlexTorresDev/custom-electron-titlebar#93]
I can't seem to be able to activate the menu using the ALT key. Whenever I press it, nothing happens. I have set the titlebar settings as follows:

```js
const titlebar = new Titlebar({
	backgroundColor: Color.fromHex('#000'),
	itemBackgroundColor: Color.fromHex('#222'),
	icon: "img/icon48.png",
	menuPosition: "bottom",
	enableMnemonics: true,
	titleHorizontalAlignment: "left",
	minimizable: true,
	maximizable: false,
});

titlebar.updateTitle(window.app_title);
```

**Desktop:**
 - OS: Windows 10 and Arch Linux
 - Electron 9.1.0
 - Node 12.14.1

**Comment by edzehoo** [comment]
has this been fixed?

**Comment by lvcabral** [comment]
This used to work in older versions, it should be prioritized higher.
